"""
Django settings for ecomm_config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zlzut%o=u9u=2-khrn4-kahuz8dcxixqzm6wq=!80ft))_7b(t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if os.getenv("ENVIRONMENT") == "production":
    DEBUG = False

ALLOWED_HOSTS = [
    "*"
    # "127.0.0.1",
    # "localhost",
    # "ecommerce-with-django-xpoy-qyhdwrffu.vercel.app",
    # "ecommerce-with-django-xpoy-2qsyuz2d9.vercel.app",  # add this one too
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'store',
    'cart',
    'payment'
]

if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = 'ecomm_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'store/templates',BASE_DIR / 'cart/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "context_processors.categories_processor",
                "context_processors.cart_processor",


            ],
        },
    },
]

WSGI_APPLICATION = 'ecomm_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'





TAILWIND_APP_NAME = 'store'

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# INTERNAL_IPS = [
#     "127.0.0.1:8000",
#     "localhost:8000",
# ]

from dotenv import load_dotenv
load_dotenv()

STRIPE_SECRET_KEY=os.getenv("STRIPE_SECRET_KEY")

STRIPE_PUBLIC_KEY=os.getenv("STRIPE_PUBLIC_KEY")

WEBHOOK_ACCOUNT_ID=os.getenv("WEBHOOK_ACCOUNT_ID")

STRIPE_WEBHOOK_SECRET=os.getenv("STRIPE_WEBHOOK_SECRET")