# Generated by Django 5.2.6 on 2025-09-21 12:05

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[store.validators.validatePhone]),
        ),
    ]
